name: interpolator
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - jupyterlab
  - pip
  - pip:
      - seaborn
      - ipywidgets
